# Generated by Django 2.2.3 on 2020-10-28 05:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ClickhouseSQLLog',
            fields=[
                ('object_id', models.CharField(default='', max_length=50, primary_key=True, serialize=False, verbose_name='主键')),
                ('app_name', models.CharField(blank=True, max_length=200, null=True, verbose_name='应用名称')),
                ('gen_datetime', models.DateField(max_length=500, verbose_name='时间')),
                ('log', models.CharField(max_length=10000, verbose_name='日志信息')),
            ],
            options={
                'verbose_name': 'ClickhouseSQL日志',
                'verbose_name_plural': 'ClickhouseSQL日志',
                'db_table': 'ClickhouseSQL日志表',
            },
        ),
        migrations.CreateModel(
            name='FinkSQLLog',
            fields=[
                ('object_id', models.CharField(default='', max_length=50, primary_key=True, serialize=False, verbose_name='主键')),
                ('app_name', models.CharField(blank=True, max_length=200, null=True, verbose_name='应用名称')),
                ('gen_datetime', models.DateField(max_length=500, verbose_name='时间')),
                ('log', models.CharField(max_length=10000, verbose_name='日志信息')),
            ],
            options={
                'verbose_name': 'FlinkSQL日志',
                'verbose_name_plural': 'FlinkSQL日志',
                'db_table': 'FlinkSQL日志表',
            },
        ),
        migrations.CreateModel(
            name='Kafka2CHLog',
            fields=[
                ('object_id', models.CharField(default='', max_length=50, primary_key=True, serialize=False, verbose_name='主键')),
                ('app_name', models.CharField(blank=True, max_length=200, null=True, verbose_name='应用名称')),
                ('gen_datetime', models.DateField(max_length=500, verbose_name='时间')),
                ('log', models.CharField(max_length=10000, verbose_name='日志信息')),
            ],
            options={
                'verbose_name': 'Kafka2CH日志',
                'verbose_name_plural': 'Kafka2CH日志',
                'db_table': 'Kafka2CH日志表',
            },
        ),
        migrations.CreateModel(
            name='Kafka2HbaseLog',
            fields=[
                ('object_id', models.CharField(default='', max_length=50, primary_key=True, serialize=False, verbose_name='主键')),
                ('app_name', models.CharField(blank=True, max_length=200, null=True, verbose_name='应用名称')),
                ('gen_datetime', models.DateField(max_length=500, verbose_name='时间')),
                ('log', models.CharField(max_length=10000, verbose_name='日志信息')),
            ],
            options={
                'verbose_name': 'Kafka2Hbase日志',
                'verbose_name_plural': 'Kafka2Hbase日志',
                'db_table': 'Kafka2Hbase日志表',
            },
        ),
    ]
