# Generated by Django 2.2.3 on 2020-10-28 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BaseInfo',
            fields=[
                ('app_name', models.CharField(max_length=200, primary_key=True, serialize=False, verbose_name='应用名称')),
                ('kafka_cluster', models.CharField(choices=[('kafkacluster1', '集群1'), ('kafkacluster2', '集群2')], default='kafkacluster1', max_length=50, verbose_name='Kafka/MQ集群')),
                ('kafka_topic', models.CharField(max_length=100, verbose_name='数据Topic')),
                ('clickhouse_cluster', models.CharField(choices=[('clickhousecluster1', '集群1'), ('clickhousecluster2', '集群2')], default='clickhousecluster1', max_length=50, verbose_name='Clickhouse集群')),
                ('clickhouse_database', models.CharField(choices=[('clickhousedb1', '库1'), ('clickhousedb2', '库2')], default='clickhousedb1', max_length=50, verbose_name='Clickhouse库名')),
                ('clickhouse_tablename', models.CharField(max_length=50, verbose_name='Clickhouse表名')),
            ],
            options={
                'verbose_name': '基本信息',
                'verbose_name_plural': '基本信息',
                'db_table': 'Kafka2CH基本信息表',
            },
        ),
        migrations.CreateModel(
            name='ClickhouseTableInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_index', models.CharField(max_length=100, verbose_name='排序索引')),
                ('simple_field', models.CharField(max_length=100, verbose_name='抽样字段')),
                ('query_size', models.CharField(choices=[('DEFAULT', '默认'), ('OTHER', '其他')], default='DEFAULT', max_length=100, verbose_name='查询粒度')),
                ('partition_size', models.CharField(choices=[('DEFAULT', '默认'), ('OTHER', '其他')], default='DEFAULT', max_length=100, verbose_name='分区粒度')),
                ('partition_field', models.CharField(choices=[('DEFAULT', '默认'), ('OTHER', '其他')], default='DEFAULT', max_length=100, verbose_name='分区字段')),
                ('hold_time', models.CharField(max_length=100, verbose_name='数据保留时间')),
                ('app_name', models.CharField(max_length=200, verbose_name='关联应用名称')),
            ],
            options={
                'verbose_name': 'CH建表参数',
                'verbose_name_plural': 'CH建表参数',
                'db_table': 'CH建表参数表',
            },
        ),
        migrations.CreateModel(
            name='Kafka2CHMatch',
            fields=[
                ('app_name', models.CharField(max_length=200, primary_key=True, serialize=False, verbose_name='kafka字段')),
                ('kafka_cluster', models.CharField(max_length=100, verbose_name='kafka字段类型')),
                ('ch_type', models.CharField(max_length=100, verbose_name='CH消费类型')),
                ('ch_property', models.CharField(max_length=100, verbose_name='CH属性')),
                ('ch_expression', models.CharField(max_length=100, verbose_name='CH表达式')),
                ('ch_field_name', models.CharField(max_length=100, verbose_name='CH字段名')),
            ],
            options={
                'verbose_name': 'Schema展示',
                'verbose_name_plural': 'Schema展示',
                'db_table': 'Schema展示表',
            },
        ),
    ]
