# Generated by Django 2.2.3 on 2020-10-28 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kafka2clickhouse', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='JobInfo',
            fields=[
                ('configID', models.CharField(max_length=200, primary_key=True, serialize=False, verbose_name='配置ID')),
                ('app_name', models.CharField(default='应用名称', max_length=50)),
                ('change_time', models.DateField(max_length=100, verbose_name='更新时间')),
                ('kafka_cluster', models.CharField(max_length=50, verbose_name='Kafka/MQ集群')),
                ('kafka_topic', models.CharField(max_length=100, verbose_name='Topic')),
                ('clickhouse_cluster', models.CharField(max_length=50, verbose_name='Clickhouse集群')),
                ('clickhouse_database', models.CharField(max_length=50, verbose_name='Clickhouse库名')),
                ('clickhouse_tablename', models.CharField(max_length=50, verbose_name='Clickhouse表名')),
                ('state', models.CharField(max_length=50, verbose_name='状态')),
            ],
            options={
                'verbose_name': '任务导入',
                'verbose_name_plural': '任务导入',
                'db_table': 'Kafka2CH任务导入表',
            },
        ),
    ]
